### ISSUE TITLE
.../deps/rpc-common/src/mgos_rpc.c:185:52: error: implicit declaration of function 'mgos_uptime' 

### ISSUE THREAD

**Issue by aleksmarcelo** [mongoose-os-libs/rpc-common#9]
In a local build

## error:

/home/aleks/projetos/saquarema/mos_bomba_esp32_ok/deps/rpc-common/src/mgos_rpc.c: In function 'mgos_print_sys_info':
/home/aleks/projetos/saquarema/mos_bomba_esp32_ok/deps/rpc-common/src/mgos_rpc.c:185:52: error: implicit declaration of function 'mgos_uptime' [-Werror=implicit-function-declaration]
       mgos_sys_ro_vars_get_arch(), (unsigned long) mgos_uptime(),

## possible solution (?!)
include "mgos_time.h" in c or header mgos_rpc

**Comment by rojer** [comment]
we already do: https://github.com/mongoose-os-libs/rpc-common/blob/725b0a71a4af29e3f1d13cd7d38c868bc2729c5b/src/mgos_rpc.c#L43

it looks like you're using mongoose-os repo at master but rpc-common at 2.17.0
